name: 🧪 CI • Build 🔧 Lint Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: 🔧 Build, Test and Lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [26]

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🅿️ Uses pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: 🧰 Setup Node.js and cache pnpm
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: 📦 Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: 🔍 Check for vulnerable dependencies
        run: pnpm audit --audit-level=moderate

      - name: 🧠 TypeScript type check
        run: pnpm exec tsc --noEmit

      - name: 🧹 Lint code with ESLint
        run: pnpm lint

      - name: 🧪 Run unit tests
        run: pnpm test --if-present

      - name: ⚙️ Build project
        run: pnpm build